examples:
  disable:
    - if: IDF_VERSION_MAJOR < 5 and CONFIG_NAME not in ["esp-box", "esp-box-lite", "esp32_s3_eye", "esp_wrover_kit", "esp32_s3_korvo_2"]
      reason: Example depends on BSP, which is supported only for IDF >= 5.0
