name: Build BSP examples

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        include:
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 1
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 2
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 3
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 4
          - idf_ver: "latest"
            parallel_count: 5
            parallel_index: 5
          - idf_ver: "release-v4.4"
            parallel_count: 1
            parallel_index: 1
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build ESP-BSP examples
        shell: bash
        run: |
          export IDF_EXTRA_ACTIONS_PATH=${GITHUB_WORKSPACE}/examples
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager ruamel.yaml idf-build-apps --upgrade
          idf-build-apps find
          idf-build-apps build --parallel-count ${{ matrix.parallel_count }} --parallel-index ${{ matrix.parallel_index }}
