name: Build BSP examples

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["latest"]
        parallel_index: [1,2,3,4,5] # This must be from 1 to 'parallel_count' defined in .idf_build_apps.toml
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build ESP-BSP examples
        shell: bash
        run: |
          export IDF_EXTRA_ACTIONS_PATH=${GITHUB_WORKSPACE}/examples
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager ruamel.yaml idf-build-apps --upgrade
          idf-build-apps find
          idf-build-apps build --parallel-index ${{ matrix.parallel_index }}
